#
# (C) Copyright 2004-2017 Centec Networks (suzhou) Co., LTD.
# Jay Cao <caoj@centecnetworks.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y   += cpu.o
obj-$(CONFIG_CTC_SEC_BOOT) += efuse.o
obj-$(CONFIG_CTC_SEC_BOOT) += image-verify.o
obj-$(CONFIG_SPL_BUILD) += spl.o
obj-$(CONFIG_DIRECT_QSPI) += lowlevel_init.o
obj-$(CONFIG_CTC_SWITCH) += switch.o
