#
# (C) Copyright 2004-2017 Centec Networks (suzhou) Co., LTD.
# Jay Cao <caoj@centecnetworks.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-$(CONFIG_SYS_CTC_DDR) += ddr_clock.o
obj-$(CONFIG_SYS_CTC_DDR) += ddr_init.o
obj-$(CONFIG_SYS_CTC_DDR) += ddr_timing.o
obj-$(CONFIG_SYS_CTC_DDR) += ddr_display.o
